### ISSUE TITLE
Typology-processor - remove channel feature

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [frmscoe/typology-processor#169]
## User Story Statement
**As a** Tazama system operator
**I want** to remove the channel feature
**so that** the system is as simple as possible to maintain and configure for an inexperienced user; and
**so that** the system performs as fast as possible at the lowest possible cost

## Acceptance Criteria
1.  Bump the FRMS-coe-lib version
2. Bump the FRMS-coe-startup-lib
3. The typology processor interrogates the network map at startup - processing to be updated
4. Channel-based processing of rule aggregation and channel-based processing of the typology result to be removed
5. Migrate documentation from Confluence (@Sandy-at-Tazama & @Justus-at-Tazama)
6.  Update documentation as follows:
## Overview/Description/Introduction
What does the processor do?
## Inputs (Docstring documentation)
What does the processor need?
## Internal process flow (diagram, with descriptions)
How does the processor work?
## Outputs (linked to diagram exit points)
What does the processor deliver?
## Environment variables (table)
How can the processor behaviour be configured?
## Deployment
How is the processor deployed?
## Operation
How is the processor operated? (Stopped, Restarted, etc)
## Troubleshooting
What are typical issues and their remedies

see TMS-configuration - remove channel feature [#2](https://github.com/frmscoe/tms-configuration/issues/2)

**Comment by Sandy-at-Tazama** [comment]
CADProc moved into TadProc already

**Comment by Sandy-at-Tazama** [comment]
CADProc moved into TadProc already

**Comment by Sandy-at-Tazama** [comment]
Accidently closed

**Comment by Justus-at-Tazama** [comment]
Prep a integration test for the typology processor - @Sandy-at-Tazama
