### ISSUE TITLE
Typology-processor - remove true/false rule result outcome

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [frmscoe/typology-processor#170]
## Background

The impact of rule “Result”: false/true on the typology processing is artificial and the specific “subRuleRef” is already sufficiently unique to determine the weighting in the typology processor.  https://github.com/frmscoe/General-Issues/issues/351

## User Story Statement

**As a** Tazama system operator
**I want** to remove the true and false rule outcomes; and
**I want** to replace the true/false weighting attributes with a weighting attribute
**so that** the system is as simple as possible to maintain and configure for an inexperienced user; and
**so that** the system performs as fast as possible at the lowest possible cost

## Acceptance Criteria
1. Bump the FRMS-coe-lib version
2. Bump the FRMS-coe-startup-lib
3. Update to the typology configuration class/object type
4. Update typology configs to replace true/false weighting attributes with a  weighting ('wght') attribute
5. Allow the typology processor to receive the rule result that now excludes the `result` attribute
6. Changes to the result payload structure out of the typology processor
7. Update documentation

## As-is - with True/False
```JSON
    "desc": "Rule-901 Typology",
    "id": "typology-processor@1.0.0",
    "cfg": "999@1.0.0",
    "workflow": {
      "alertThreshold": 200,
      "interdictionThreshold": 400
    },
    "rules": [
      {
        "id": "901@1.0.0",
        "cfg": "1.0.0",
        "ref": ".err",
        "true": 100,
        "false": 0        
      },
      {
        "id": "901@1.0.0",
        "cfg": "1.0.0",
        "ref": ".x01",
        "true": 200,
        "false": 0       
      },
```

## To-be - without true/false and with wght

```JSON
  {
    "_key": "999@1.0.0",
    "desc": "Rule-901 Typology",
    "id": "typology-processor@1.0.0",
    "cfg": "999@1.0.0",
    "workflow": {
      "alertThreshold": 200,
      "interdictionThreshold": 400
    },
    "rules": [
      {
        "id": "901@1.0.0",
        "cfg": "1.0.0",
        "ref": ".err",
        "wght": 0
      },
      {
        "id": "901@1.0.0",
        "cfg": "1.0.0",
        "ref": ".x01",
        "wght": 0
      },
      {
```

**Comment by Justus-at-Tazama** [comment]
Prep a integration test for the typology processor - @Sandy-at-Tazama
