### ISSUE TITLE
Misconfigured workflows

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [frmscoe/typology-processor#226]
Some workflows have duplicate definitions:
bench.yml - There is also a bench.yaml
milestone.yml - There is also a milestone.yaml
scorecard.yaml - There is also a milestone.yaml

The docker-image-build.yaml workflow is failing because a token was not provided to install frms-coe libraries.
An explicit eslint workflow is not needed as linting is already being done in the node.js.yml workflow in the lint job.

## Acceptance Criteria
[ ] For consistency, stick to one file extension for workflows (yml)
[ ] Ensure no duplicate jobs
[ ] Test all workflows and make sure they work as intended

**Comment by vorsterk** [comment]
Workflows removed from Typology processor. Scott will relook at the additional ones he added.
